spring.application.name=demo
# ----------------------------------------
# PostgreSQL Database Connection
# ----------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/tailor-automation-system
spring.datasource.username=postgres
spring.datasource.password=Mayank2307@?
spring.datasource.driver-class-name=org.postgresql.Driver

# ----------------------------------------
# Hibernate / JPA Settings
# ----------------------------------------
# Shows the actual SQL queries Spring writes in your console (Great for debugging)
spring.jpa.show-sql=true

# Formats the SQL in the console so it is easy to read
spring.jpa.properties.hibernate.format_sql=true

# How Spring handles your database schema updates
spring.jpa.hibernate.ddl-auto=update