/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KarigarRouteImport } from './routes/karigar'
import { Route as CounterRouteImport } from './routes/counter'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokenTokenIdRouteImport } from './routes/token.$tokenId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KarigarRoute = KarigarRouteImport.update({
  id: '/karigar',
  path: '/karigar',
  getParentRoute: () => rootRouteImport,
} as any)
const CounterRoute = CounterRouteImport.update({
  id: '/counter',
  path: '/counter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenTokenIdRoute = TokenTokenIdRouteImport.update({
  id: '/token/$tokenId',
  path: '/token/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/counter': typeof CounterRoute
  '/karigar': typeof KarigarRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/token/$tokenId': typeof TokenTokenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/counter': typeof CounterRoute
  '/karigar': typeof KarigarRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/token/$tokenId': typeof TokenTokenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/counter': typeof CounterRoute
  '/karigar': typeof KarigarRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/token/$tokenId': typeof TokenTokenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/counter'
    | '/karigar'
    | '/login'
    | '/settings'
    | '/token/$tokenId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/counter' | '/karigar' | '/login' | '/settings' | '/token/$tokenId'
  id:
    | '__root__'
    | '/'
    | '/counter'
    | '/karigar'
    | '/login'
    | '/settings'
    | '/token/$tokenId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CounterRoute: typeof CounterRoute
  KarigarRoute: typeof KarigarRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  TokenTokenIdRoute: typeof TokenTokenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karigar': {
      id: '/karigar'
      path: '/karigar'
      fullPath: '/karigar'
      preLoaderRoute: typeof KarigarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counter': {
      id: '/counter'
      path: '/counter'
      fullPath: '/counter'
      preLoaderRoute: typeof CounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$tokenId': {
      id: '/token/$tokenId'
      path: '/token/$tokenId'
      fullPath: '/token/$tokenId'
      preLoaderRoute: typeof TokenTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CounterRoute: CounterRoute,
  KarigarRoute: KarigarRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  TokenTokenIdRoute: TokenTokenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
